ml_feature_store:

  primary_feature_table:
    population_health_dashboard

  target_features:

    - chronic_disease_count
    - total_encounters
    - unique_medications
    - total_claim_cost
    - avg_bmi
    - avg_glucose
    - avg_hba1c
    - polypharmacy_flag
    - high_cost_patient_flag
    - high_treatment_complexity_flag

  risk_target:
    population_health_risk_category
