catalog: healthcare_catalog

schemas:
  bronze: bronze
  silver: silver
  gold: gold

storage:
  raw_fhir_volume: /Volumes/healthcare_catalog/bronze/raw_fhir_files/

tables:
  patient: patient_clean
  encounter: encounter_clean
  condition: condition_clean
  observation: observation_clean
  procedure: procedure_clean
  medication: medication_request_clean
  immunization: immunization_clean
  careplan: careplan_clean
  allergy: allergy_intolerance_clean
  claim: claim_clean
